spring:
  mvc.pathmatch.matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  batch:
    job.enabled: true